name: lanayago_mobile
description: "Application mobile LanaYaGo - Transport et livraison"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # État management
  provider: ^6.1.2
  
  # HTTP et API
  http: ^1.2.2
  dio: ^5.4.3+1
  
  # Stockage local
  shared_preferences: ^2.2.3
  
  # Géolocalisation et cartes
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  
  # WebSocket pour notifications temps réel
  web_socket_channel: ^2.4.5
  
  # UI et icônes
  cupertino_icons: ^1.0.8
  
  # Utils
  intl: ^0.19.0
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/